# Numpy Questions for revision

1. What is a vector?

In NumPy, a vector is a one-dimensional array. It is similar to a Python list, but is more efficient for certain operations and is always homogenous (i.e., all elements of the array have the same data type).

In [1]:
import numpy as np

2. How do you represent vectors using a Python list? Give an example.

In [4]:
v = np.array([1.0, 2.5, 3.7, 4])
print(v)

[1.  2.5 3.7 4. ]


3. What is a dot product of two vectors?

The dot product (also called the scalar product or inner product) of two vectors is a scalar value that is obtained by multiplying the corresponding elements of the two vectors and summing the results.

4. Write a function to compute the dot product of two vectors.

In [6]:
def dot_product(a,b):
    return a@b

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])


dot_product = dot_product(a,b)

print(dot_product)

32


5. What is Numpy?

NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

6. How do you install Numpy?

In [7]:
!pip install numpy --upgrade --quiet

7. How do you import the numpy module?

8. What does it mean to import a module with an alias? Give an example.

In [9]:
import numpy as np

9. What is the commonly used alias for numpy?

np or anything else can be given as alias

10. What is a Numpy array?

A NumPy array is a multi-dimensional array of homogenous (same type) elements. It is similar to a Python list, but is more efficient for certain operations and is always homogenous (i.e., all elements of the array have the same data type). NumPy arrays are used to represent large arrays of numerical data, such as images, audio signals, and other types of data.

11. How do you create a Numpy array? Give an example.

In [13]:
lst = [1, 2, 3, 4]
a = np.array(lst)
print(a)

[1 2 3 4]


12. What is the type of Numpy arrays?

In [12]:
type(a)

numpy.ndarray

13. How do you access the elements of a Numpy array?

You can access the elements of a NumPy array using indices or slices.

To access a single element of a NumPy array, you can use the square bracket notation and specify the index of the element you want to access

14. How do you compute the dot product of two vectors using Numpy?

To compute the dot product of two vectors using NumPy, you can use the dot function. This function takes two arrays as arguments and returns the dot product of the arrays.

15. What happens if you try to compute the dot product of two vectors which have different sizes?

If you try to compute the dot product of two vectors which have different sizes, NumPy will raise a ValueError exception. This is because the dot product of two vectors is defined only for vectors of the same size.

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)


16. How do you compute the element-wise product of two Numpy arrays?

To compute the element-wise product of two NumPy arrays, you can use the * operator or the multiply function.

The * operator performs element-wise multiplication of the two arrays and returns a new array with the results. 

Both the * operator and the multiply function work for both 1D and 2D arrays. For 2D arrays, the element-wise product is calculated for each element of the arrays.

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a * b

d = np.empty(a.shape)

np.multiply(a, b, out=d)

print(c)
print(d)

[ 4 10 18]
[ 4. 10. 18.]


17. How do you compute the sum of all the elements in a Numpy array?

To compute the sum of all the elements in a NumPy array, you can use the sum function. This function takes an array as an argument and returns the sum of all the elements in the array.

In [18]:
a = np.array([[1, 2], [3, 4]])

s = np.sum(a, axis=0)# Compute the sum of all the elements along axis 0 (columns)

print(s)

s = np.sum(a, axis=1)# Compute the sum of all the elements along axis 1 (rows)

print(s)

[4 6]
[3 7]


18. What are the benefits of using Numpy arrays over Python lists for operating on numerical data?

Performance: NumPy arrays are implemented in C and are more efficient than Python lists for certain operations, such as element-wise arithmetic, dot product, and more. NumPy arrays can also be processed in parallel using multi-core processors, which can speed up certain operations.

Memory efficiency: NumPy arrays use less memory than Python lists, because they store the data in a contiguous block of memory and use a fixed data type. This can be important when working with large datasets that do not fit in memory.

Functionality: NumPy provides a large set of functions and methods that allow you to perform various operations on arrays, such as element-wise arithmetic, linear algebra, statistical analysis, and more. These functions are optimized for speed and are much faster than writing a loop in Python.

Integration with other libraries: NumPy arrays are used as the basic data structure in many popular libraries such as scikit-learn, TensorFlow, and PyTorch. These libraries provide efficient implementations of various algorithms that operate on NumPy arrays, and using NumPy arrays can make it easier to integrate your code with these libraries.

19. Why do Numpy array operations have better performance compared to Python functions and loops?

NumPy array operations are much faster than Python functions and loops because they are implemented in C, are optimized for speed, and can be parallelized using multi-core processors. This makes NumPy an essential library for scientific computing with Python.

20. Illustrate the performance difference between Numpy array operations and Python loops using an example.

In [21]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)

In [22]:
%%time
dot_product = np.dot(a, b)

Wall time: 24 ms


In [23]:
%%time
for i in range(len(a)):
    dot_product += a[i] * b[i]

Wall time: 1.05 s


21. What are multi-dimensional Numpy arrays?

NumPy arrays can have any number of dimensions, and are sometimes called "multi-dimensional arrays." NumPy arrays with more than one dimension are called "2D arrays," "3D arrays," and so on, depending on the number of dimensions.

22. Illustrate the creation of Numpy arrays with 2, 3, and 4 dimensions

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6]])

b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

c = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])

print(a)
print(b)
print(c)

[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]


23. How do you inspect the number of dimensions and the length along each dimension in a Numpy array?

To inspect the number of dimensions and the length along each dimension in a NumPy array, you can use the ndim attribute and the shape attribute of the array.

In [27]:
# Create a 2D NumPy array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)

# Create a 3D NumPy array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b.ndim)

# Create a 4D NumPy array
c = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(c.ndim)

2
3
4


In [28]:
# Create a 2D NumPy array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)

# Create a 3D NumPy array
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b.shape)

# Create a 4D NumPy array
c = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]])
print(c.shape)

(2, 3)
(2, 2, 2)
(2, 2, 2, 2)


24. Can the elements of a Numpy array have different data types?

Yes, the elements of a NumPy array can have different data types. By default, NumPy tries to infer the data type of the elements of the array based on the values that are passed to it.

In [29]:
a = np.array([1, 2, 3.5, 4.5, 5])

print(a.dtype)

float64


25. How do you check the data type of the elements of a Numpy array?

To check the data type of the elements of a NumPy array, you can use the dtype attribute of the array. The dtype attribute returns the data type of the elements of the array as a NumPy data type object.

In [30]:
a = np.array([1, 2, 3.5, 4.5, 5], dtype='int32')

print(a.dtype)

int32


26. What is the data type of a Numpy array?

A NumPy array has a data type that specifies the type of the elements of the array. The data type of a NumPy array is stored in the dtype attribute of the array.

27. What is the difference between a matrix and a 2D Numpy array?

In general, a matrix is a two-dimensional array of numbers that is used to represent linear transformations. A matrix is usually written in the form of a rectangular array of numbers, with each element of the array representing a number in the matrix.

On the other hand, a NumPy array is a multi-dimensional array of elements that can be of any data type. A NumPy array can have any number of dimensions, and a 2D NumPy array is an array of rows, where each row is an array of elements.
In terms of representation and operations, matrices and 2D NumPy arrays are similar, and you can use a 2D NumPy array to represent a matrix in Python. 

28. How do you perform matrix multiplication using Numpy?

You can perform matrix multiplication using NumPy by using the dot function or matmul function from the NumPy library

29. What is the @ operator used for in Numpy?

In NumPy, the @ operator is an infix operator that performs matrix multiplication. It was introduced in Python 3.5 as a way to perform matrix multiplication in a more concise and intuitive way

30. What is the CSV file format?

CSV stands for Comma Separated Values. It is a simple file format that is used to store tabular data, such as a spreadsheet or database table.

31.How do you read data from a CSV file using Numpy?

You can use NumPy's loadtxt function to read data from a CSV file and store it in a NumPy array. The loadtxt function is a convenient function for reading data from a simple, tabular text file, such as a CSV file.

32. How do you concatenate two Numpy arrays?

You can use the concatenate function from NumPy to concatenate two NumPy arrays. The concatenate function combines two or more arrays along a given axis and returns a new array that is the concatenation of the input arrays.

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = np.concatenate((a, b))
print(c)


[1 2 3 4 5 6]


33. What is the purpose of the axis argument of np.concatenate?

In NumPy, the axis argument of the concatenate function specifies the axis along which the arrays are concatenated. It determines the direction in which the arrays are combined, and the shape of the resulting array.

In [34]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Concatenate the arrays along axis 0
c = np.concatenate((a, b), axis=0)
print(c)
print("\n")
# Concatenate the arrays along axis 1
d = np.concatenate((a, b), axis=1)
print(d)


[[1 2]
 [3 4]
 [5 6]
 [7 8]]


[[1 2 5 6]
 [3 4 7 8]]


34. When are two Numpy arrays compatible for concatenation?

In NumPy, two arrays are compatible for concatenation if they have the same shape along all dimensions except the one along which they are being concatenated

35. Give an example of two Numpy arrays that can be concatenated.

In [35]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

36. Give an example of two Numpy arrays that cannot be concatenated.

In [36]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6, 7], [8, 9, 10]])

37. What is the purpose of the np.reshape function?

38. What does it mean to “reshape” a Numpy array?

The reshape function in NumPy is used to change the shape of an array. It creates a new array with a different shape from the original array, without changing the data itself.

In [37]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a.reshape((3, 2))
print(b) 

[[1 2]
 [3 4]
 [5 6]]


39. How do you write a numpy array into a CSV file?

You can use the numpy.savetxt function to write a NumPy array to a CSV file. The savetxt function takes the array and the file object as arguments, and writes the array to the file in CSV format.

In [38]:
a = np.array([[1, 2, 3], [4, 5, 6]])

# Save the array to a CSV file, with elements formatted as integers
np.savetxt("array.csv", a, delimiter=",", fmt="%d")


40. Give some examples of Numpy functions for performing mathematical operations.

abs: Calculate the absolute value of an array.
    
exp: Calculate the exponential of an array.
    
sqrt: Calculate the square root of an array.
    
sin, cos, tan: Calculate the sine, cosine, and tangent of an array.
    
arcsin, arccos, arctan: Calculate the inverse sine, cosine, and tangent of an array.
    
log, log10, log2: Calculate the natural logarithm, base-10 logarithm, and base-2 logarithm of an array.
    
mean: Calculate the mean value of an array.
    
median: Calculate the median value of an array.
    
std: Calculate the standard deviation of an array.
    
corrcoef: Calculate the correlation coefficient of an array.
    
sort: Sort the elements of an array.

In [39]:
# Create an array with random values
a = np.random.rand(5)

# Calculate the absolute value, exponential, and square root of the array
b = np.abs(a)
c = np.exp(a)
d = np.sqrt(a)

# Calculate the sine, cosine, and tangent of the array
e = np.sin(a)
f = np.cos(a)
g = np.tan(a)

# Calculate the mean and standard deviation of the array
mean = np.mean(a)
std = np.std(a)

# Sort the array
h = np.sort(a)

print(a)  
print(b)  
print(c)  
print(d)  
print(e)  
print(f)  
print(g)  
print(mean) 
print(std)


[0.22423086 0.07856559 0.90543733 0.70196379 0.48685482]
[0.22423086 0.07856559 0.90543733 0.70196379 0.48685482]
[1.25135988 1.0817343  2.47301321 2.01771118 1.62719035]
[0.47353021 0.28029554 0.95154471 0.83783279 0.69774982]
[0.22235654 0.07848479 0.78669521 0.64571843 0.46784847]
[0.97496542 0.99691531 0.61734159 0.76357561 0.8838087 ]
[0.22806608 0.07872764 1.27432725 0.84565094 0.5293549 ]
0.4794104775315744
0.30228381865763027


41. Give some examples of Numpy functions for performing array manipulation.

reshape: Change the shape of an array.
    
resize: Change the size and shape of an array.
    
expand_dims: Add a new dimension to an array.
    
squeeze: Remove single-dimensional entries from the shape of an array.
    
flatten: Collapse an array into a single dimension.
    
transpose: Reverse or permute the dimensions of an array.
    
concatenate: Join two or more arrays along a specified axis.
    
vstack, hstack: Stack arrays vertically or horizontally.
    
split: Split an array into multiple subarrays.
    
tile: Repeat an array multiple times.
    
repeat: Repeat the elements of an array multiple times.

In [43]:
# Create a 2D array
a = np.array([[1, 2], [3, 4]])

# Change the shape of the array
b = a.reshape((4, 1))
print(b,'\n')  

# Resize the array
c = np.resize(a, (3, 3))
print(c,'\n') 

# Add a new dimension to the array
d = np.expand_dims(a, axis=2)
print(d,'\n')  

# Remove single-dimensional entries from the shape of the array
e = np.squeeze(a)
print(e,'\n')

[[1]
 [2]
 [3]
 [4]] 

[[1 2 3]
 [4 1 2]
 [3 4 1]] 

[[[1]
  [2]]

 [[3]
  [4]]] 

[[1 2]
 [3 4]] 



42. Give some examples of Numpy functions for performing linear algebra.

dot: Compute the dot product of two arrays.
    
vdot: Compute the dot product of two vectors.
    
matmul: Compute the matrix product of two arrays.
    
transpose: Transpose an array.
    
linalg.inv: Compute the inverse of a matrix.
    
linalg.solve: Solve a linear system of equations.
    
linalg.eig: Compute the eigenvalues and eigenvectors of a matrix.

In [45]:
import numpy as np

# Create two 2D arrays
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

# Compute the dot product of the arrays
c = np.dot(a, b)
print(c,'\n')  

# Compute the dot product of two vectors
d = np.array([1, 2, 3])
e = np.array([4, 5, 6])
f = np.vdot(d, e)
print(f,'\n')  

# Compute the matrix product of the arrays
g = np.matmul(a, b)
print(g,'\n') 

# Transpose the array
h = np.transpose(a)
print(h,'\n')  

# Compute the inverse of a matrix
i = np.linalg.inv(a)
print(i,'\n')

# Solve a linear system of equations
A = np.array([[1, 1], [2, 3]])
b = np.array([1, 2])
x = np.linalg.solve(A, b)
print(x,'\n') 

[[19 22]
 [43 50]] 

32 

[[19 22]
 [43 50]] 

[[1 3]
 [2 4]] 

[[-2.   1. ]
 [ 1.5 -0.5]] 

[ 1. -0.] 



43. Give some examples of Numpy functions for performing statistical operations.

mean: Calculate the mean value of an array.
    
median: Calculate the median value of an array.
    
std: Calculate the standard deviation of an array.
    
var: Calculate the variance of an array.
    
min, max: Calculate the minimum and maximum value of an array.
    
argmin, argmax: Calculate the indices of the minimum and maximum value of an array.
    
percentile: Calculate the nth percentile of an array.
    
corrcoef: Calculate the correlation coefficient of an array.

In [47]:
# Create an array with random values
a = np.random.rand(5)

# Calculate the mean, median, and standard deviation of the array
mean = np.mean(a)
median = np.median(a)
std = np.std(a)

# Calculate the variance of the array
var = np.var(a)

# Calculate the minimum and maximum value of the array
min = np.min(a)
max = np.max(a)

# Calculate the indices of the minimum and maximum value of the array
argmin = np.argmin(a)
argmax = np.argmax(a)

# Calculate the 50th percentile of the array
percentile = np.percentile(a, 50)

# Calculate the correlation coefficient of the array
corrcoef = np.corrcoef(a)

print(a,'\n')  
print(mean,'\n')
print(median,'\n')
print(std,'\n','\n')  
print(var,'\n')
print(min,'\n')
print(max,'\n')
print(argmin,'\n')
print(argmax,'\n')
print(percentile,'\n')
print(corrcoef,'\n')  


[0.98415549 0.25658061 0.49449161 0.67941391 0.1796052 ] 

0.5188493628731854 

0.49449160824751437 

0.292149128680316 
 

0.08535111338866785 

0.17960519739371772 

0.9841554890877442 

4 

0 

0.49449160824751437 

1.0 



44. How do you find the right Numpy function for a specific operation or use case?

Look at the NumPy documentation: The NumPy documentation is a comprehensive resource that lists all of the functions and methods available in NumPy, along with detailed descriptions and examples. You can access the documentation at https://numpy.org/.

Use the NumPy function search: The NumPy function search is a tool that allows you to search for functions by keyword. To use the function search, go to https://numpy.org/doc/stable/reference/routines.html and enter your search terms in the search box at the top of the page.

Use the dir function: You can use the Python dir function to list all of the functions and methods available in NumPy. For example, you can use dir(np) to list all of the functions and methods in the NumPy module.

Use online resources: There are many online resources that provide examples and explanations of how to use NumPy functions. You can use these resources to learn about different NumPy functions and how to use them.

Experiment and try out different functions: If you are not sure which NumPy function to use, you can try out different functions to see which one works best for your use case.

45. Where can you see a list of all the Numpy array functions and operations?

Use the NumPy function search: The NumPy function search is a tool that allows you to search for functions by keyword. To use the function search, go to https://numpy.org/doc/stable/reference/routines.html and enter your search terms in the search box at the top of the page.

46. What are the arithmetic operators supported by Numpy arrays? Illustrate with examples.

+: Add two arrays element-wise.
    
-: Subtract two arrays element-wise.
    
*: Multiply two arrays element-wise.
    
/: Divide two arrays element-wise.
    
//: Divide two arrays element-wise and round down to the nearest integer.
    
**: Raise one array to the power of another element-wise.

In [49]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
d = a - b
e = a * b
f = a / b
g = a // b
h = a ** b
print(c,'\n',d,'\n',e,'\n',f,'\n',g,'\n',h,'\n')

[5 7 9] 
 [-3 -3 -3] 
 [ 4 10 18] 
 [0.25 0.4  0.5 ] 
 [0 0 0] 
 [  1  32 729] 



47. What is array broadcasting? How is it useful? Illustrate with an example

Array broadcasting is a powerful feature in NumPy that allows you to perform element-wise operations on arrays with different shapes. Array broadcasting works by "stretching" or "copying" the smaller array so that it has the same shape as the larger array, and then performing the element-wise operation on the two arrays.

Array broadcasting is useful because it allows you to write concise code for operations that would otherwise require loops or other explicit array manipulation. It also enables you to perform element-wise operations on arrays with different shapes, which is not possible with standard Python operators.

In [50]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
b = np.array([7, 8, 9])

# Perform an element-wise operation using array broadcasting
c = a + b
print(c) 

[[ 8 10 12]
 [11 13 15]]


48. Give some examples of arrays that are compatible for broadcasting?

In [51]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])

# Create a 1D array
b = np.array([7, 8, 9])

49. Give some examples of arrays that are not compatible for broadcasting?

In [52]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([7, 8])

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10]])

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array(7)

50. What are the comparison operators supported by Numpy arrays? Illustrate with examples.

51. How do you access a specific subarray or slice from a Numpy array?

In [54]:
# Create a 2D array
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Access the second row of the array
b = a[1,:]
print(b) 

# Access the second column of the array
c = a[:,1]
print(c) 

# Access a subarray with a shape of (2,2) starting at index (1,1)
d = a[1:3,1:3]
print(d) 

[4 5 6]
[2 5 8]
[[5 6]
 [8 9]]


52. Illustrate array indexing and slicing in multi-dimensional Numpy arrays with some examples.

In [55]:
# Create a 3D array
a = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

# Access the second element of the first dimension
b = a[1]
print(b) 

# Access the second element of the second dimension
c = a[:,1]
print(c)  

# Access the second element of the third dimension
d = a[:,:,1]
print(d)  

# Access a subarray with a shape of (2,2,1) starting at index (1,1,1)
e = a[1:3,1:3,1:2]
print(e) 

[[5 6]
 [7 8]]
[[3 4]
 [7 8]]
[[2 4]
 [6 8]]
[[[8]]]


53. How do you create a Numpy array with a given shape containing all zeros?

In [56]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

54. How do you create a Numpy array with a given shape containing all ones?

In [57]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

55. How do you create an identity matrix of a given shape?

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

56. How do you create a random vector of a given length?

In [59]:
np.random.rand(6)

array([0.56643693, 0.87429306, 0.01557085, 0.29752758, 0.57192847,
       0.78284939])

57. How do you create a Numpy array with a given shape with a fixed value for each element?

In [60]:
np.full([2,3],69)

array([[69, 69, 69],
       [69, 69, 69]])

58. How do you create a Numpy array with a given shape containing randomly initialized elements?

In [62]:
np.random.rand(3, 4)

array([[0.5207106 , 0.86315293, 0.38858578, 0.75622029],
       [0.63260343, 0.50848346, 0.72674817, 0.30796134],
       [0.28547747, 0.91152167, 0.17705786, 0.21642813]])

59. What is the difference between np.random.rand and np.random.randn? Illustrate with examples.

The numpy.random.rand function generates random values between 0 and 1 from a uniform distribution, while the numpy.random.randn function generates random values from a normal distribution with mean 0 and standard deviation 1.

In [64]:
np.random.randn(2,2)

array([[ 0.18931932, -0.8865772 ],
       [ 0.24330439,  0.23245972]])

60. What is the difference between np.arange and np.linspace? Illustrate with examples.

The numpy.arange function generates a sequence of evenly spaced values within a given range, while the numpy.linspace function generates a sequence of evenly spaced values over a specified interval.

In [65]:
np.linspace(3,27,9)

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27.])

In [66]:
np.arange(6, 10)

array([6, 7, 8, 9])